
import { ColorTheme } from './types';

export const COLOR_THEMES: ColorTheme[] = [
  {
    name: '🔵 블루-그레이',
    description: '차분하고 전문적인 느낌',
    colors: {
      primary: '#1a73e8',
      primaryDark: '#004d99',
      secondary: '#5f6368',
      background: '#f8f9fa',
      text: '#3c4043',
      highlightBg: '#e8f0fe',
      infoBoxBg: '#e8f4fd',
      infoBoxBorder: '#1a73e8',
      warningBoxBg: '#fce8e6',
      warningBoxBorder: '#d93025',
      tableHeaderBg: '#e8eaed',
      tableBorder: '#dadce0',
      tableEvenRowBg: '#f1f3f4',
    },
  },
  {
    name: '🌿 그린-오렌지',
    description: '활기차고 친근한 느낌',
    colors: {
      primary: '#34a853',
      primaryDark: '#1e8e3e',
      secondary: '#ea8600',
      background: '#f1f8e9',
      text: '#333333',
      highlightBg: '#fef6e0',
      infoBoxBg: '#e6f4ea',
      infoBoxBorder: '#34a853',
      warningBoxBg: '#fde293',
      warningBoxBorder: '#f9ab00',
      tableHeaderBg: '#e6f4ea',
      tableBorder: '#a5d6a7',
      tableEvenRowBg: '#f1f8e9',
    },
  },
  {
    name: '💜 퍼플-옐로우',
    description: '세련되고 창의적인 느낌',
    colors: {
      primary: '#8e44ad',
      primaryDark: '#6200ea',
      secondary: '#f1c40f',
      background: '#fdf6e3',
      text: '#2c3e50',
      highlightBg: '#fcf8e3',
      infoBoxBg: '#f3e5f5',
      infoBoxBorder: '#8e44ad',
      warningBoxBg: '#fff9c4',
      warningBoxBorder: '#f1c40f',
      tableHeaderBg: '#f3e5f5',
      tableBorder: '#ce93d8',
      tableEvenRowBg: '#faf3fb',
    },
  },
  {
    name: '🍵 틸-라이트그레이',
    description: '안정적이고 현대적인 느낌',
    colors: {
      primary: '#00796b',
      primaryDark: '#004d40',
      secondary: '#607d8b',
      background: '#eceff1',
      text: '#263238',
      highlightBg: '#e0f2f1',
      infoBoxBg: '#e0f7fa',
      infoBoxBorder: '#00796b',
      warningBoxBg: '#ffebee',
      warningBoxBorder: '#c62828',
      tableHeaderBg: '#cfd8dc',
      tableBorder: '#b0bec5',
      tableEvenRowBg: '#eceff1',
    },
  },
  {
    name: '🧱 테라코타-라이트그레이',
    description: '따뜻하고 편안한 느낌',
    colors: {
      primary: '#e57373',
      primaryDark: '#c62828',
      secondary: '#757575',
      background: '#fafafa',
      text: '#424242',
      highlightBg: '#ffcdd2',
      infoBoxBg: '#fbe9e7',
      infoBoxBorder: '#ff8a65',
      warningBoxBg: '#fff3e0',
      warningBoxBorder: '#ffa726',
      tableHeaderBg: '#eeeeee',
      tableBorder: '#e0e0e0',
      tableEvenRowBg: '#f5f5f5',
    },
  },
   {
    name: '👔 클래식 블루',
    description: '신뢰할 수 있고 안정적인 느낌',
    colors: {
      primary: '#0f4c81',
      primaryDark: '#002f6c',
      secondary: '#77aaff',
      background: '#f0f4f8',
      text: '#333333',
      highlightBg: '#e3f2fd',
      infoBoxBg: '#e3f2fd',
      infoBoxBorder: '#0f4c81',
      warningBoxBg: '#ffebee',
      warningBoxBorder: '#d32f2f',
      tableHeaderBg: '#d6e4f0',
      tableBorder: '#b0bec5',
      tableEvenRowBg: '#f0f4f8',
    },
  },
  {
    name: '🌳 네이처 그린',
    description: '생기 있고 조화로운 느낌',
    colors: {
      primary: '#2e7d32',
      primaryDark: '#005005',
      secondary: '#aed581',
      background: '#f1f8e9',
      text: '#212121',
      highlightBg: '#dcedc8',
      infoBoxBg: '#e8f5e9',
      infoBoxBorder: '#2e7d32',
      warningBoxBg: '#fffde7',
      warningBoxBorder: '#fbc02d',
      tableHeaderBg: '#c8e6c9',
      tableBorder: '#a5d6a7',
      tableEvenRowBg: '#f1f8e9',
    },
  },
  {
    name: '🌲 포레스트 그린',
    description: '깊고 안정적인 자연의 느낌',
    colors: {
      primary: '#00796b',
      primaryDark: '#004d40',
      secondary: '#607d8b',
      background: '#f7f9f9',
      text: '#333333',
      highlightBg: '#fff9c4',
      infoBoxBg: '#e0f2f7',
      infoBoxBorder: '#4dd0e1',
      warningBoxBg: '#fffde7',
      warningBoxBorder: '#fbc02d',
      tableHeaderBg: '#e0f7fa',
      tableBorder: '#e0e0e0',
      tableEvenRowBg: '#f5f5f5',
    },
  },
  {
    name: '🧱 브라운-베이지',
    description: '따뜻하고 아늑한 흙의 느낌',
    colors: {
      primary: '#a0522d',
      primaryDark: '#8b4513',
      secondary: '#757575',
      background: '#fdfbf8',
      text: '#444444',
      highlightBg: '#fff9c4',
      infoBoxBg: '#fff3e0',
      infoBoxBorder: '#ffb74d',
      warningBoxBg: '#fffde7',
      warningBoxBorder: '#fbc02d',
      tableHeaderBg: '#f4f4f4',
      tableBorder: '#d3d3d3',
      tableEvenRowBg: '#eeeeee',
    },
  },
  {
    name: '🌌 미드나잇 퍼플',
    description: '신비롭고 창의적인 느낌',
    colors: {
      primary: '#6a1b9a',
      primaryDark: '#4a148c',
      secondary: '#757575',
      background: '#f9f6fc',
      text: '#444444',
      highlightBg: '#fff9c4',
      infoBoxBg: '#ede7f6',
      infoBoxBorder: '#9575cd',
      warningBoxBg: '#fffde7',
      warningBoxBorder: '#fbc02d',
      tableHeaderBg: '#f3e5f5',
      tableBorder: '#e1bee7',
      tableEvenRowBg: '#fafafa',
    },
  },
  {
    name: '🌅 선셋 코랄',
    description: '따뜻하고 감성적인 노을 느낌',
    colors: {
      primary: '#FF7043',
      primaryDark: '#D84315',
      secondary: '#FFCA28',
      background: '#FFF8E1',
      text: '#3E2723',
      highlightBg: '#FFF3E0',
      infoBoxBg: '#FFF3E0',
      infoBoxBorder: '#FF7043',
      warningBoxBg: '#FBE9E7',
      warningBoxBorder: '#FFAB91',
      tableHeaderBg: '#FFECB3',
      tableBorder: '#FFE082',
      tableEvenRowBg: '#FFF8E1',
    },
  },
  {
    name: '🌊 오션 브리즈',
    description: '시원하고 상쾌한 바다 느낌',
    colors: {
      primary: '#00ACC1',
      primaryDark: '#00838F',
      secondary: '#00838F',
      background: '#E0F7FA',
      text: '#006064',
      highlightBg: '#B2EBF2',
      infoBoxBg: '#E0F7FA',
      infoBoxBorder: '#00ACC1',
      warningBoxBg: '#FFEBEE',
      warningBoxBorder: '#EF5350',
      tableHeaderBg: '#B2EBF2',
      tableBorder: '#4DD0E1',
      tableEvenRowBg: '#E0F7FA',
    },
  },
  {
    name: '🩰 라벤더 소프트',
    description: '부드럽고 차분한 파스텔 감성',
    colors: {
      primary: '#9575CD',
      primaryDark: '#5E35B1',
      secondary: '#F06292',
      background: '#F3E5F5',
      text: '#4A148C',
      highlightBg: '#E1BEE7',
      infoBoxBg: '#F3E5F5',
      infoBoxBorder: '#9575CD',
      warningBoxBg: '#FCE4EC',
      warningBoxBorder: '#F06292',
      tableHeaderBg: '#E1BEE7',
      tableBorder: '#BA68C8',
      tableEvenRowBg: '#F3E5F5',
    },
  },
  {
    name: '🖤 모던 모노크롬',
    description: '깔끔하고 현대적인 미니멀리즘',
    colors: {
      primary: '#424242',
      primaryDark: '#212121',
      secondary: '#757575',
      background: '#FFFFFF',
      text: '#212121',
      highlightBg: '#F5F5F5',
      infoBoxBg: '#FAFAFA',
      infoBoxBorder: '#9E9E9E',
      warningBoxBg: '#FFEBEE',
      warningBoxBorder: '#D32F2F',
      tableHeaderBg: '#EEEEEE',
      tableBorder: '#BDBDBD',
      tableEvenRowBg: '#FAFAFA',
    },
  },
  {
    name: '⚜️ 로얄 네이비',
    description: '고급스럽고 신뢰감 있는 비즈니스 느낌',
    colors: {
      primary: '#1A237E',
      primaryDark: '#000051',
      secondary: '#FBC02D',
      background: '#E8EAF6',
      text: '#1A237E',
      highlightBg: '#C5CAE9',
      infoBoxBg: '#E8EAF6',
      infoBoxBorder: '#3949AB',
      warningBoxBg: '#FFFDE7',
      warningBoxBorder: '#FBC02D',
      tableHeaderBg: '#C5CAE9',
      tableBorder: '#7986CB',
      tableEvenRowBg: '#E8EAF6',
    },
  },
];
